package com.pavanpathro.androidcountrypicker;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Pavan on 11/03/18.
 */

public class CountryCodePickerUtil {

    public static int REQUEST_CODE_COUNTRY_CODE_PICKER = 1;

    public static String KEY_SELECTED_COUNTRY = "SELECTED_COUNTRY";

    public static List<Country> getListOfCountries() {
        List<Country> countryList = new ArrayList<>();
        countryList.add(new Country("AD", "Andorra", "+376", R.drawable.flag_ad));
        countryList.add(new Country("AE", "United Arab Emirates", "+971", R.drawable.flag_ae));
        countryList.add(new Country("AF", "Afghanistan", "+93", R.drawable.flag_af));
        countryList.add(new Country("AG", "Antigua and Barbuda", "+1", R.drawable.flag_ag));
        countryList.add(new Country("AG", "Antigua and Barbuda", "+1", R.drawable.flag_ag));
        countryList.add(new Country("AI", "Anguilla", "+1", R.drawable.flag_ai));
        countryList.add(new Country("AL", "Albania", "+355", R.drawable.flag_al));
        countryList.add(new Country("AM", "Armenia", "+374", R.drawable.flag_am));
        countryList.add(new Country("AO", "Angola", "+244", R.drawable.flag_ao));
        countryList.add(new Country("AQ", "Antarctica", "+672", R.drawable.flag_aq));
        countryList.add(new Country("AR", "Argentina", "+54", R.drawable.flag_ar));
        countryList.add(new Country("AS", "AmericanSamoa", "+1", R.drawable.flag_as));
        countryList.add(new Country("AT", "Austria", "+43", R.drawable.flag_at));
        countryList.add(new Country("AU", "Australia", "+61", R.drawable.flag_au));
        countryList.add(new Country("AW", "Aruba", "+297", R.drawable.flag_aw));
        countryList.add(new Country("AX", "Åland Islands", "+358", R.drawable.flag_ax));
        countryList.add(new Country("AZ", "Azerbaijan", "+994", R.drawable.flag_az));
        countryList.add(new Country("BA", "Bosnia and Herzegovina", "+387", R.drawable.flag_ba));
        countryList.add(new Country("BB", "Barbados", "+1", R.drawable.flag_bb));
        countryList.add(new Country("BD", "Bangladesh", "+880", R.drawable.flag_bd));
        countryList.add(new Country("BE", "Belgium", "+32", R.drawable.flag_be));
        countryList.add(new Country("BF", "Burkina Faso", "+226", R.drawable.flag_bf));
        countryList.add(new Country("BG", "Bulgaria", "+359", R.drawable.flag_bg));
        countryList.add(new Country("BH", "Bahrain", "+973", R.drawable.flag_bh));
        countryList.add(new Country("BI", "Burundi", "+257", R.drawable.flag_bi));
        countryList.add(new Country("BJ", "Benin", "+229", R.drawable.flag_bj));
        countryList.add(new Country("BL", "Saint Barthélemy", "+590", R.drawable.flag_bl));
        countryList.add(new Country("BM", "Bermuda", "+1", R.drawable.flag_bm));
        countryList.add(new Country("BN", "Brunei Darussalam", "+673", R.drawable.flag_bn));
        countryList.add(new Country("BO", "Bolivia, Plurinational State of", "+591", R.drawable.flag_bo));
        countryList.add(new Country("BQ", "Bonaire", "+599", R.drawable.flag_bq));
        countryList.add(new Country("BR", "Brazil", "+55", R.drawable.flag_br));
        countryList.add(new Country("BS", "Bahamas", "+1", R.drawable.flag_bs));
        countryList.add(new Country("BT", "Bhutan", "+975", R.drawable.flag_bt));
        countryList.add(new Country("BV", "Bouvet Island", "+47", R.drawable.flag_bv));
        countryList.add(new Country("BW", "Botswana", "+267", R.drawable.flag_bw));
        countryList.add(new Country("BY", "Belarus", "+375", R.drawable.flag_by));
        countryList.add(new Country("BZ", "Belize", "+501", R.drawable.flag_bz));
        countryList.add(new Country("CA", "Canada", "+1", R.drawable.flag_ca));
        countryList.add(new Country("CC", "Cocos (Keeling) Islands", "+61", R.drawable.flag_cc));
        countryList.add(new Country("CD", "Congo, The Democratic Republic of the", "+243", R.drawable.flag_cd));
        countryList.add(new Country("CF", "Central African Republic", "+236", R.drawable.flag_cf));
        countryList.add(new Country("CG", "Congo", "+242", R.drawable.flag_cg));
        countryList.add(new Country("CH", "Switzerland", "+41", R.drawable.flag_ch));
        countryList.add(new Country("CI", "Ivory Coast", "+225", R.drawable.flag_ci));
        countryList.add(new Country("CK", "Cook Islands", "+682", R.drawable.flag_ck));
        countryList.add(new Country("CL", "Chile", "+56", R.drawable.flag_cl));
        countryList.add(new Country("CM", "Cameroon", "+237", R.drawable.flag_cm));
        countryList.add(new Country("CN", "China", "+86", R.drawable.flag_cn));
        countryList.add(new Country("CO", "Colombia", "+57", R.drawable.flag_co));
        countryList.add(new Country("CR", "Costa Rica", "+506", R.drawable.flag_cr));
        countryList.add(new Country("CU", "Cuba", "+53", R.drawable.flag_cu));
        countryList.add(new Country("CV", "Cape Verde", "+238", R.drawable.flag_cv));
        countryList.add(new Country("CW", "Curacao", "+599", R.drawable.flag_cw));
        countryList.add(new Country("CX", "Christmas Island", "+61", R.drawable.flag_cx));
        countryList.add(new Country("CY", "Cyprus", "+357", R.drawable.flag_cy));
        countryList.add(new Country("CZ", "Czech Republic", "+420", R.drawable.flag_cz));
        countryList.add(new Country("DE", "Germany", "+49", R.drawable.flag_de));
        countryList.add(new Country("DJ", "Djibouti", "+253", R.drawable.flag_dj));
        countryList.add(new Country("DK", "Denmark", "+45", R.drawable.flag_dk));
        countryList.add(new Country("DM", "Dominica", "+1", R.drawable.flag_dm));
        countryList.add(new Country("DO", "Dominican Republic", "+1", R.drawable.flag_do));
        countryList.add(new Country("DZ", "Algeria", "+213", R.drawable.flag_dz));
        countryList.add(new Country("EC", "Ecuador", "+593", R.drawable.flag_ec));
        countryList.add(new Country("EE", "Estonia", "+372", R.drawable.flag_ee));
        countryList.add(new Country("EG", "Egypt", "+20", R.drawable.flag_eg));
        countryList.add(new Country("EH", "Western Sahara", "+212", R.drawable.flag_eh));
        countryList.add(new Country("ER", "Eritrea", "+291", R.drawable.flag_er));
        countryList.add(new Country("ES", "Spain", "+34", R.drawable.flag_es));
        countryList.add(new Country("ET", "Ethiopia", "+251", R.drawable.flag_et));
        countryList.add(new Country("FI", "Finland", "+358", R.drawable.flag_fi));
        countryList.add(new Country("FJ", "Fiji", "+679", R.drawable.flag_fj));
        countryList.add(new Country("FK", "Falkland Islands (Malvinas)", "+500", R.drawable.flag_fk));
        countryList.add(new Country("FM", "Micronesia, Federated States of", "+691", R.drawable.flag_fm));
        countryList.add(new Country("FO", "Faroe Islands", "+298", R.drawable.flag_fo));
        countryList.add(new Country("FR", "France", "+33", R.drawable.flag_fr));
        countryList.add(new Country("GA", "Gabon", "+241", R.drawable.flag_ga));
        countryList.add(new Country("GB", "United Kingdom", "+44", R.drawable.flag_gb));
        countryList.add(new Country("GD", "Grenada", "+1", R.drawable.flag_gd));
        countryList.add(new Country("GE", "Georgia", "+995", R.drawable.flag_ge));
        countryList.add(new Country("GF", "French Guiana", "+594", R.drawable.flag_gf));
        countryList.add(new Country("GG", "Guernsey", "+44", R.drawable.flag_gg));
        countryList.add(new Country("GH", "Ghana", "+233", R.drawable.flag_gh));
        countryList.add(new Country("GI", "Gibraltar", "+350", R.drawable.flag_gi));
        countryList.add(new Country("GL", "Greenland", "+299", R.drawable.flag_gl));
        countryList.add(new Country("GM", "Gambia", "+220", R.drawable.flag_gm));
        countryList.add(new Country("GN", "Guinea", "+224", R.drawable.flag_gn));
        countryList.add(new Country("GP", "Guadeloupe", "+590", R.drawable.flag_gp));
        countryList.add(new Country("GQ", "Equatorial Guinea", "+240", R.drawable.flag_gq));
        countryList.add(new Country("GR", "Greece", "+30", R.drawable.flag_gr));
        countryList.add(new Country("GS", "South Georgia and the South Sandwich Islands", "+500", R.drawable.flag_gs));
        countryList.add(new Country("GT", "Guatemala", "+502", R.drawable.flag_gt));
        countryList.add(new Country("GU", "Guam", "+1", R.drawable.flag_gu));
        countryList.add(new Country("GW", "Guinea-Bissau", "+245", R.drawable.flag_gw));
        countryList.add(new Country("GY", "Guyana", "+595", R.drawable.flag_gy));
        countryList.add(new Country("HK", "Hong Kong", "+852", R.drawable.flag_hk));
        countryList.add(new Country("HM", "Heard Island and McDonald Islands", "", R.drawable.flag_hm));
        countryList.add(new Country("HN", "Honduras", "+504", R.drawable.flag_hn));
        countryList.add(new Country("HR", "Croatia", "+385", R.drawable.flag_hr));
        countryList.add(new Country("HT", "Haiti", "+509", R.drawable.flag_ht));
        countryList.add(new Country("HU", "Hungary", "+36", R.drawable.flag_hu));
        countryList.add(new Country("ID", "Indonesia", "+62", R.drawable.flag_id));
        countryList.add(new Country("IE", "Ireland", "+353", R.drawable.flag_ie));
        countryList.add(new Country("IL", "Israel", "+972", R.drawable.flag_il));
        countryList.add(new Country("IM", "Isle of Man", "+44", R.drawable.flag_im));
        countryList.add(new Country("IN", "India", "+91", R.drawable.flag_in));
        countryList.add(new Country("IO", "British Indian Ocean Territory", "+246", R.drawable.flag_io));
        countryList.add(new Country("IQ", "Iraq", "+964", R.drawable.flag_iq));
        countryList.add(new Country("IR", "Iran, Islamic Republic of", "+98", R.drawable.flag_ir));
        countryList.add(new Country("IS", "Iceland", "+354", R.drawable.flag_is));
        countryList.add(new Country("IT", "Italy", "+39", R.drawable.flag_it));
        countryList.add(new Country("JE", "Jersey", "+44", R.drawable.flag_je));
        countryList.add(new Country("JM", "Jamaica", "+1", R.drawable.flag_jm));
        countryList.add(new Country("JO", "Jordan", "+962", R.drawable.flag_jo));
        countryList.add(new Country("JP", "Japan", "+81", R.drawable.flag_jp));
        countryList.add(new Country("KE", "Kenya", "+254", R.drawable.flag_ke));
        countryList.add(new Country("KG", "Kyrgyzstan", "+996", R.drawable.flag_kg));
        countryList.add(new Country("KH", "Cambodia", "+855", R.drawable.flag_kh));
        countryList.add(new Country("KI", "Kiribati", "+686", R.drawable.flag_ki));
        countryList.add(new Country("KM", "Comoros", "+269", R.drawable.flag_km));
        countryList.add(new Country("KN", "Saint Kitts and Nevis", "+1", R.drawable.flag_kn));
        countryList.add(new Country("KP", "North Korea", "+850", R.drawable.flag_kp));
        countryList.add(new Country("KR", "South Korea", "+82", R.drawable.flag_kr));
        countryList.add(new Country("KW", "Kuwait", "+965", R.drawable.flag_kw));
        countryList.add(new Country("KY", "Cayman Islands", "+345", R.drawable.flag_ky));
        countryList.add(new Country("KZ", "Kazakhstan", "+7", R.drawable.flag_kz));
        countryList.add(new Country("LA", "Lao People's Democratic Republic", "+856", R.drawable.flag_la));
        countryList.add(new Country("LB", "Lebanon", "+961", R.drawable.flag_lb));
        countryList.add(new Country("LC", "Saint Lucia", "+1", R.drawable.flag_lc));
        countryList.add(new Country("LI", "Liechtenstein", "+423", R.drawable.flag_li));
        countryList.add(new Country("LK", "Sri Lanka", "+94", R.drawable.flag_lk));
        countryList.add(new Country("LR", "Liberia", "+231", R.drawable.flag_lr));
        countryList.add(new Country("LS", "Lesotho", "+266", R.drawable.flag_ls));
        countryList.add(new Country("LT", "Lithuania", "+370", R.drawable.flag_lt));
        countryList.add(new Country("LU", "Luxembourg", "+352", R.drawable.flag_lu));
        countryList.add(new Country("LV", "Latvia", "+371", R.drawable.flag_lv));
        countryList.add(new Country("LY", "Libyan Arab Jamahiriya", "+218", R.drawable.flag_ly));
        countryList.add(new Country("MA", "Morocco", "+212", R.drawable.flag_ma));
        countryList.add(new Country("MC", "Monaco", "+377", R.drawable.flag_mc));
        countryList.add(new Country("MD", "Moldova, Republic of", "+373", R.drawable.flag_md));
        countryList.add(new Country("ME", "Montenegro", "+382", R.drawable.flag_me));
        countryList.add(new Country("MF", "Saint Martin", "+590", R.drawable.flag_mf));
        countryList.add(new Country("MG", "Madagascar", "+261", R.drawable.flag_mg));
        countryList.add(new Country("MH", "Marshall Islands", "+692", R.drawable.flag_mh));
        countryList.add(new Country("MK", "Macedonia, The Former Yugoslav Republic of", "+389", R.drawable.flag_mk));
        countryList.add(new Country("ML", "Mali", "+223", R.drawable.flag_ml));
        countryList.add(new Country("MM", "Myanmar", "+95", R.drawable.flag_mm));
        countryList.add(new Country("MN", "Mongolia", "+976", R.drawable.flag_mn));
        countryList.add(new Country("MO", "Macao", "+853", R.drawable.flag_mo));
        countryList.add(new Country("MP", "Northern Mariana Islands", "+1", R.drawable.flag_mp));
        countryList.add(new Country("MQ", "Martinique", "+596", R.drawable.flag_mq));
        countryList.add(new Country("MR", "Mauritania", "+222", R.drawable.flag_mr));
        countryList.add(new Country("MS", "Montserrat", "+1", R.drawable.flag_ms));
        countryList.add(new Country("MT", "Malta", "+356", R.drawable.flag_mt));
        countryList.add(new Country("MU", "Mauritius", "+230", R.drawable.flag_mu));
        countryList.add(new Country("MV", "Maldives", "+960", R.drawable.flag_mv));
        countryList.add(new Country("MW", "Malawi", "+265", R.drawable.flag_mw));
        countryList.add(new Country("MX", "Mexico", "+52", R.drawable.flag_mx));
        countryList.add(new Country("MY", "Malaysia", "+60", R.drawable.flag_my));
        countryList.add(new Country("MZ", "Mozambique", "+258", R.drawable.flag_mz));
        countryList.add(new Country("NA", "Namibia", "+264", R.drawable.flag_na));
        countryList.add(new Country("NC", "New Caledonia", "+687", R.drawable.flag_nc));
        countryList.add(new Country("NE", "Niger", "+227", R.drawable.flag_ne));
        countryList.add(new Country("NF", "Norfolk Island", "+672", R.drawable.flag_nf));
        countryList.add(new Country("NG", "Nigeria", "+234", R.drawable.flag_ng));
        countryList.add(new Country("NI", "Nicaragua", "+505", R.drawable.flag_ni));
        countryList.add(new Country("NL", "Netherlands", "+31", R.drawable.flag_nl));
        countryList.add(new Country("NO", "Norway", "+47", R.drawable.flag_no));
        countryList.add(new Country("NP", "Nepal", "+977", R.drawable.flag_np));
        countryList.add(new Country("NR", "Nauru", "+674", R.drawable.flag_nr));
        countryList.add(new Country("NU", "Niue", "+683", R.drawable.flag_nu));
        countryList.add(new Country("NZ", "New Zealand", "+64", R.drawable.flag_nz));
        countryList.add(new Country("OM", "Oman", "+968", R.drawable.flag_om));
        countryList.add(new Country("PA", "Panama", "+507", R.drawable.flag_pa));
        countryList.add(new Country("PE", "Peru", "+51", R.drawable.flag_pe));
        countryList.add(new Country("PF", "French Polynesia", "+689", R.drawable.flag_pf));
        countryList.add(new Country("PG", "Papua New Guinea", "+675", R.drawable.flag_pg));
        countryList.add(new Country("PH", "Philippines", "+63", R.drawable.flag_ph));
        countryList.add(new Country("PK", "Pakistan", "+92", R.drawable.flag_pk));
        countryList.add(new Country("PL", "Poland", "+48", R.drawable.flag_pl));
        countryList.add(new Country("PM", "Saint Pierre and Miquelon", "+508", R.drawable.flag_pm));
        countryList.add(new Country("PN", "Pitcairn", "+872", R.drawable.flag_pn));
        countryList.add(new Country("PR", "Puerto Rico", "+1", R.drawable.flag_pr));
        countryList.add(new Country("PS", "Palestinian Territory, Occupied", "+970", R.drawable.flag_ps));
        countryList.add(new Country("PT", "Portugal", "+351", R.drawable.flag_pt));
        countryList.add(new Country("PW", "Palau", "+680", R.drawable.flag_pw));
        countryList.add(new Country("PY", "Paraguay", "+595", R.drawable.flag_py));
        countryList.add(new Country("QA", "Qatar", "+974", R.drawable.flag_qa));
        countryList.add(new Country("RE", "Réunion", "+262", R.drawable.flag_re));
        countryList.add(new Country("RO", "Romania", "+40", R.drawable.flag_ro));
        countryList.add(new Country("RS", "Serbia", "+381", R.drawable.flag_rs));
        countryList.add(new Country("RU", "Russia", "+7", R.drawable.flag_ru));
        countryList.add(new Country("RW", "Rwanda", "+250", R.drawable.flag_rw));
        countryList.add(new Country("SA", "Saudi Arabia", "+966", R.drawable.flag_sa));
        countryList.add(new Country("SB", "Solomon Islands", "+677", R.drawable.flag_sb));
        countryList.add(new Country("SC", "Seychelles", "+248", R.drawable.flag_sc));
        countryList.add(new Country("SD", "Sudan", "+249", R.drawable.flag_sd));
        countryList.add(new Country("SE", "Sweden", "+46", R.drawable.flag_se));
        countryList.add(new Country("SG", "Singapore", "+65", R.drawable.flag_sg));
        countryList.add(new Country("SH", "Saint Helena, Ascension and Tristan Da Cunha", "+290", R.drawable.flag_sh));
        countryList.add(new Country("SI", "Slovenia", "+386", R.drawable.flag_si));
        countryList.add(new Country("SJ", "Svalbard and Jan Mayen", "+47", R.drawable.flag_sj));
        countryList.add(new Country("SK", "Slovakia", "+421", R.drawable.flag_sk));
        countryList.add(new Country("SL", "Sierra Leone", "+232", R.drawable.flag_sl));
        countryList.add(new Country("SM", "San Marino", "+378", R.drawable.flag_sm));
        countryList.add(new Country("SN", "Senegal", "+221", R.drawable.flag_sn));
        countryList.add(new Country("SO", "Somalia", "+252", R.drawable.flag_so));
        countryList.add(new Country("SR", "Suriname", "+597", R.drawable.flag_sr));
        countryList.add(new Country("SS", "South Sudan", "+211", R.drawable.flag_ss));
        countryList.add(new Country("ST", "Sao Tome and Principe", "+239", R.drawable.flag_st));
        countryList.add(new Country("SV", "El Salvador", "+503", R.drawable.flag_sv));
        countryList.add(new Country("SX", "  Sint Maarten", "+1", R.drawable.flag_sx));
        countryList.add(new Country("SY", "Syrian Arab Republic", "+963", R.drawable.flag_sy));
        countryList.add(new Country("SZ", "Swaziland", "+268", R.drawable.flag_sz));
        countryList.add(new Country("TC", "Turks and Caicos Islands", "+1", R.drawable.flag_tc));
        countryList.add(new Country("TD", "Chad", "+235", R.drawable.flag_td));
        countryList.add(new Country("TF", "French Southern Territories", "+262", R.drawable.flag_tf));
        countryList.add(new Country("TG", "Togo", "+228", R.drawable.flag_tg));
        countryList.add(new Country("TH", "Thailand", "+66", R.drawable.flag_th));
        countryList.add(new Country("TJ", "Tajikistan", "+992", R.drawable.flag_tj));
        countryList.add(new Country("TK", "Tokelau", "+690", R.drawable.flag_tk));
        countryList.add(new Country("TL", "East Timor", "+670", R.drawable.flag_tl));
        countryList.add(new Country("TM", "Turkmenistan", "+993", R.drawable.flag_tm));
        countryList.add(new Country("TN", "Tunisia", "+216", R.drawable.flag_tn));
        countryList.add(new Country("TO", "Tonga", "+676", R.drawable.flag_to));
        countryList.add(new Country("TR", "Turkey", "+90", R.drawable.flag_tr));
        countryList.add(new Country("TT", "Trinidad and Tobago", "+1", R.drawable.flag_tt));
        countryList.add(new Country("TV", "Tuvalu", "+688", R.drawable.flag_tv));
        countryList.add(new Country("TW", "Taiwan", "+886", R.drawable.flag_tw));
        countryList.add(new Country("TZ", "Tanzania, United Republic of", "+255", R.drawable.flag_tz));
        countryList.add(new Country("UA", "Ukraine", "+380", R.drawable.flag_ua));
        countryList.add(new Country("UG", "Uganda", "+256", R.drawable.flag_ug));
        countryList.add(new Country("UM", "U.S. Minor Outlying Islands", "", R.drawable.flag_um));
        countryList.add(new Country("US", "United States", "+1", R.drawable.flag_us));
        countryList.add(new Country("UY", "Uruguay", "+598", R.drawable.flag_uy));
        countryList.add(new Country("UZ", "Uzbekistan", "+998", R.drawable.flag_uz));
        countryList.add(new Country("VA", "Holy See (Vatican City State)", "+379", R.drawable.flag_va));
        countryList.add(new Country("VC", "Saint Vincent and the Grenadines", "+1", R.drawable.flag_vc));
        countryList.add(new Country("VE", "Venezuela, Bolivarian Republic of", "+58", R.drawable.flag_ve));
        countryList.add(new Country("VG", "Virgin Islands, British", "+1", R.drawable.flag_vg));
        countryList.add(new Country("VI", "Virgin Islands, U.S.", "+1", R.drawable.flag_vi));
        countryList.add(new Country("VN", "Viet Nam", "+84", R.drawable.flag_vn));
        countryList.add(new Country("VU", "Vanuatu", "+678", R.drawable.flag_vu));
        countryList.add(new Country("WF", "Wallis and Futuna", "+681", R.drawable.flag_wf));
        countryList.add(new Country("WS", "Samoa", "+685", R.drawable.flag_ws));
        countryList.add(new Country("XK", "Kosovo", "+383", R.drawable.flag_xk));
        countryList.add(new Country("YE", "Yemen", "+967", R.drawable.flag_ye));
        countryList.add(new Country("YT", "Mayotte", "+262", R.drawable.flag_yt));
        countryList.add(new Country("ZA", "South Africa", "+27", R.drawable.flag_za));
        countryList.add(new Country("ZM", "Zambia", "+260", R.drawable.flag_zm));
        countryList.add(new Country("ZW", "Zimbabwe", "+263", R.drawable.flag_zw));

        return countryList;
    }

    public static List<Country> getListOfFilteredCountries(String searchedText) {
        List<Country> newCountryList = new ArrayList<>();
        List<Country> countryList = getListOfCountries();
        for (int index = 0; index < countryList.size(); index++) {
            Country country = countryList.get(index);
            if (country.getName().toLowerCase().contains(searchedText) || country.getDialCode().toLowerCase().contains(searchedText) || country.getCode().toLowerCase().contains(searchedText)) {
                newCountryList.add(country);
            }
        }

        return newCountryList;
    }

}
